### ISSUE TITLE
How to Contact

### ISSUE THREAD

**Issue by mostdoqe** [Junai22/nezuko.js#1]
Hello, I would like to get in touch with you, do you have a discord or telegram?

Thanks

**Comment by nachitodev** [comment]
Hey you can add me on discord:
Junai#0622

**Comment by mostdoqe** [comment]
> Junai#622

You are missing a number    Junai#622 doesn't exist

**Comment by nachitodev** [comment]
Junai# 0622, idk why github is deleting the 0
